name: First Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello-action
        run: echo "hellow world"
      - name: Print Goodbye-action
        run: echo "Done - bye !"
